//////////////////////////////////
//    ECE-593 Project           //
//    Multiprocessor System     //
//    Milestone 5 - UVM        //
/////////////////////////////////

class mp_coverage extends uvm_subscriber #(mp_transaction);

    // UVM factory registration
    `uvm_component_utils(mp_coverage)

    // Handle to last sampled transaction
    mp_transaction tr;

    // Covergroup definition - samples via explicit function call
    covergroup op_cov with function sample(mp_transaction t);
        option.per_instance = 1;
        option.name         = "Multiprocessor_Coverage";

        // All 4 cores must be exercised
        CP_CORE: coverpoint t.core_id {
            bins core_0 = {0};
            bins core_1 = {1};
            bins core_2 = {2};
            bins core_3 = {3};
        }

        // All opcodes / instruction classes must be exercised
        CP_OPCODE: coverpoint t.opcode {
            bins NOP     = {4'b0000};
            bins ADD     = {4'b0001};
            bins AND     = {4'b0010};
            bins SUB     = {4'b0011};
            bins MUL     = {4'b0100};
            bins LOAD    = {4'b0101};
            bins STORE   = {4'b0110};
            bins SHR     = {4'b0111};
            bins SHL     = {4'b1000};
            bins SPL_0   = {4'b1001};
            bins SPL_1   = {4'b1010};
            bins SPL_2   = {4'b1011};
            bins SPL_3   = {4'b1100};
            bins SPL_4   = {4'b1101};
            illegal_bins INVALID = {[4'b1110:4'b1111]};
        }

        // Memory address regions (11-bit = 2KB)
        CP_ADDR: coverpoint t.addr {
            bins low_mem  = {[0:511]};
            bins mid_mem  = {[512:1535]};
            bins high_mem = {[1536:2047]};
        }

        // Operand corner cases
        CP_OPERAND_A: coverpoint t.A {
            bins zero   = {8'h00};
            bins max    = {8'hFF};
            bins others = {[8'h01:8'hFE]};
        }

        CP_OPERAND_B: coverpoint t.B {
            bins zero   = {8'h00};
            bins max    = {8'hFF};
            bins others = {[8'h01:8'hFE]};
        }

        // Cross: every core must run every instruction class
        CROSS_CORE_OP: cross CP_CORE, CP_OPCODE;

        // Cross: memory ops must hit all address regions
        CROSS_MEM_REGION: cross CP_OPCODE, CP_ADDR {
            ignore_bins non_mem = CROSS_MEM_REGION with
                (!(CP_OPCODE inside {4'b0101, 4'b0110}));
        }
    endgroup

    // Constructor
    function new(string name = "mp_coverage", uvm_component parent = null);
        super.new(name, parent);
        op_cov = new();
    endfunction

    // Called by analysis port when monitor sends a transaction
    virtual function void write(mp_transaction t);
        this.tr = t;
        op_cov.sample(t);
    endfunction

    // Report total coverage only — individual coverpoint get_coverage()
    // calls on named coverpoints crash UVM 1.1d during report_phase
    // (SIGSEGV on null handle). Full per-bin detail is in the UCDB
    // and func_cov_report_TOTAL.txt generated by vcover report.
    function void report_phase(uvm_phase phase);
        `uvm_info("COVERAGE", "========================================", UVM_LOW)
        `uvm_info("COVERAGE", "       FUNCTIONAL COVERAGE REPORT       ", UVM_LOW)
        `uvm_info("COVERAGE", "========================================", UVM_LOW)
        `uvm_info("COVERAGE", $sformatf("  Total Coverage : %0.2f%%", op_cov.get_coverage()), UVM_LOW)
        `uvm_info("COVERAGE", "  Full bin detail: doc/func_cov_report_TOTAL.txt", UVM_LOW)
        `uvm_info("COVERAGE", "========================================", UVM_LOW)
    endfunction

endclass
